#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Check if .env file exists.
if [ ! -f .env ]; then
    # If not, copy .env.example to .env
    cp .env.example .env
fi

composer install

# Check if the APP_KEY environment variable is set and not empty.
if [ -z "$APP_KEY" ]; then
    # if empty, set a value.
    php artisan key:generate
fi

php artisan migrate

# Check if a certificate to sign the signatures exists.
if [ ! -f storage/app/certificate.crt ]; then
    # If not, create one.
    openssl req -x509 -nodes -days 365000 -newkey rsa:1024 -keyout storage/app/certificate.crt -out storage/app/certificate.crt -subj "/C=/ST=/L=/O=$APP_NAME/OU=/CN=$APP_URL"
fi

# Check if .env.testing file exists.
if [ ! -f .env.testing ]; then
    # If not, copy .env.example to .env.testing
    cp .env.example .env.testing
    # Generate APP_KEY
    php artisan key:generate --env=testing
fi

# Run database migrations in the testing environment and run the tests.
php artisan key:generate --env=testing
php artisan migrate --env=testing
php artisan test

if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
